variables:
  IMAGE_NAME: docker.io/fpob/tox


build:
  image: docker.io/library/docker:stable
  services:
    - docker.io/library/docker:stable-dind
  stage: build
  script:
    - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD docker.io
    - docker build -t $IMAGE_NAME:latest .
    - docker run $IMAGE_NAME:latest tox --version
    - docker run -v $PWD/tests:/workdir -w /workdir $IMAGE_NAME:latest tox
    - docker push $IMAGE_NAME:latest
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
