stages:
  - build
  - test
  - publish


.docker:
  image: docker:stable
  services:
    - docker:stable-dind


build:
  extends: .docker
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA


test:
  stage: test
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  script:
    - cd tests
    - tox


.publish:
  extends: .docker
  stage: publish
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA $REGISTRY_IMAGE:latest
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD $REGISTRY
    - docker push $REGISTRY_IMAGE:latest
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

publish-gitlab:
  extends: .publish
  variables:
    REGISTRY: $CI_REGISTRY
    REGISTRY_USER: $CI_REGISTRY_USER
    REGISTRY_PASSWORD: $CI_REGISTRY_PASSWORD
    REGISTRY_IMAGE: $CI_REGISTRY_IMAGE

publish-dockerhub:
  extends: .publish
  variables:
    REGISTRY: docker.io
    REGISTRY_USER: $DOCKERHUB_USER
    REGISTRY_PASSWORD: $DOCKERHUB_PASSWORD
    REGISTRY_IMAGE: docker.io/fpob/tox
