stages:
  - prepare
  - build-py
  - build
  - test
  - publish


.docker:
  image: docker:stable
  services:
    - docker:stable-dind


prepare-build-image:
  extends: .docker
  stage: prepare
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/build:$CI_COMMIT_SHORT_SHA build
    - docker push $CI_REGISTRY_IMAGE/build:$CI_COMMIT_SHORT_SHA


build-python:
  image: $CI_REGISTRY_IMAGE/build:$CI_COMMIT_SHORT_SHA
  stage: build-py
  script:
    - /scripts/build-python.sh $VERSION
    - mkdir -p opt && mv /opt/python$VERSION opt
  artifacts:
    paths:
      - opt/python$VERSION
    expire_in: 1 day
  parallel:
    matrix:
      - VERSION:
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'

build-pypy:
  image: $CI_REGISTRY_IMAGE/build:$CI_COMMIT_SHORT_SHA
  stage: build-py
  script:
    - /scripts/build-pypy.sh $PYTHON_VERSION $PYPY_VERSION
    - mkdir -p opt && mv /opt/pypy$PYTHON_VERSION opt
  artifacts:
    paths:
      - opt/pypy$PYTHON_VERSION
    expire_in: 1 day
  parallel:
    matrix:
      - PYTHON_VERSION:
          - '3.7'
          - '3.8'
        PYPY_VERSION: '7.3'


build-latest:
  extends: .docker
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build
        --build-arg DEFAULT_PYTHON=3.10
        --build-arg DEFAULT_PYPY=3.8
        -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA


test-latest:
  stage: test
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  dependencies: []
  script:
    - cd tests
    - tox
  variables:
    TOXENV: py37,py38,py39,py310,pypy37,pypy38


.publish-latest:
  extends: .docker
  stage: publish
  dependencies: []
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA $REGISTRY_IMAGE:latest
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD $REGISTRY
    - docker push $REGISTRY_IMAGE:latest
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

publish-gitlab-latest:
  extends: .publish-latest
  variables:
    REGISTRY: $CI_REGISTRY
    REGISTRY_USER: $CI_REGISTRY_USER
    REGISTRY_PASSWORD: $CI_REGISTRY_PASSWORD
    REGISTRY_IMAGE: $CI_REGISTRY_IMAGE

publish-dockerhub-latest:
  extends: .publish-latest
  variables:
    REGISTRY: docker.io
    REGISTRY_USER: $DOCKERHUB_USER
    REGISTRY_PASSWORD: $DOCKERHUB_PASSWORD
    REGISTRY_IMAGE: docker.io/fpob/tox
